services:
  db:
    image: postgres:15
    container_name: backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supplychain
    ports:
      - "5432:5432"
    volumes:
      - supplychain-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d supplychain"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-web
    command:
      - /bin/sh
      - -c
      - |
          until pg_isready -h db -p 5432 -U postgres -d supplychain; do
            echo "waiting for db..."
            sleep 1
          done
          echo "DB ready."
          PGPASSWORD=password psql -h db -U postgres -d supplychain -f /app/analytics_order_view.sql
          exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ../sql/analytics/analytics_order_view.sql:/app/analytics_order_view.sql:ro
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/supplychain
      PGPASSWORD: password
    depends_on:
      db:
        condition: service_healthy

volumes:
  supplychain-data: