services:
  db:
    image: postgres:15
    container_name: backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supplychain
    ports:
      - "5432:5432"
    volumes:
      - supplychain-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-web
    command: >
      sh -c "
        until psql postgresql://postgres:password@db:5432/supplychain -c '\q' 2>/dev/null;
        do
          echo 'waiting for db...';
          sleep 1;
        done;

        echo 'DB ready, applying views...';

        psql postgresql://postgres:password@db:5432/supplychain -f /app/sql/analytics_views.sql 2>/dev/null || true;

        echo 'Starting FastAPI...';

        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/supplychain
    depends_on:
      - db

volumes:
  supplychain-data: